#!/usr/bin/env bash

set -x

if [ "$1" != "-r" ];then
  # layman -S && \
  emaint sync -a
fi
emerge -1 --noreplace sys-apps/portage ;\
emerge -uvDNU @world && \
emerge @live-rebuild && \
emerge @preserved-rebuild && \
revdep-rebuild
# eix-update
# perl-cleaner --all
# cpanm --self-upgrade
# cpan-outdated -p | cpanm
# perl-cleaner --all
# revdep-rebuild
systemctl daemon-reload
emerge -pc
echo "** FINISHED **"

